on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: acrmnoskoski.azurecr.io
        username: ${{ secrets.acr_acrmnoskoski_username }}
        password: ${{ secrets.acr_acrmnoskoski_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/src/analytics/1.0" -f  "src/analytics/1.0/Dockerfile" -t acrmnoskoski.azurecr.io/aksdev:${{ github.sha }} --label dockerfile-path=src/analytics/1.0/Dockerfile
        docker push acrmnoskoski.azurecr.io/aksdev:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksdev_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks-dev8c72 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks-dev8c72`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks-dev8c72
        container-registry-url: acrmnoskoski.azurecr.io
        container-registry-username: ${{ secrets.acr_acrmnoskoski_username }}
        container-registry-password: ${{ secrets.acr_acrmnoskoski_password }}
        secret-name: aksdevdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks-dev8c72
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          acrmnoskoski.azurecr.io/aksdev:${{ github.sha }}
        imagepullsecrets: |
          aksdevdockerauth
